/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppHumigadget {
    }
    interface AppRoot {
    }
    interface AppScan {
    }
    interface AppTest {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppHumigadgetElement extends Components.AppHumigadget, HTMLStencilElement {
    }
    var HTMLAppHumigadgetElement: {
        prototype: HTMLAppHumigadgetElement;
        new (): HTMLAppHumigadgetElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppScanElement extends Components.AppScan, HTMLStencilElement {
    }
    var HTMLAppScanElement: {
        prototype: HTMLAppScanElement;
        new (): HTMLAppScanElement;
    };
    interface HTMLAppTestElement extends Components.AppTest, HTMLStencilElement {
    }
    var HTMLAppTestElement: {
        prototype: HTMLAppTestElement;
        new (): HTMLAppTestElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-humigadget": HTMLAppHumigadgetElement;
        "app-root": HTMLAppRootElement;
        "app-scan": HTMLAppScanElement;
        "app-test": HTMLAppTestElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppHumigadget {
    }
    interface AppRoot {
    }
    interface AppScan {
    }
    interface AppTest {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-humigadget": AppHumigadget;
        "app-root": AppRoot;
        "app-scan": AppScan;
        "app-test": AppTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-humigadget": LocalJSX.AppHumigadget & JSXBase.HTMLAttributes<HTMLAppHumigadgetElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-scan": LocalJSX.AppScan & JSXBase.HTMLAttributes<HTMLAppScanElement>;
            "app-test": LocalJSX.AppTest & JSXBase.HTMLAttributes<HTMLAppTestElement>;
        }
    }
}
